data:
  name: "FreiHAND"
  path: "/content/FreiHAND_pub_v2/"
  save_root: "/content/refine_net/"

train:
  batch_size: 2
  num_classes: 1
  epochs: 1
  loss_type: "bce"
  checkpoint_path: null
  learning_rate: 0.00001
  weight_decay: 0
  gamma: 0.9

